# Please, copy this file to config.yaml before use the program and set your own values

# Maze dimensions. Min 2x2. Max 400x400. Cell size in pixels (min 10). In case of configure incorrect values,
# the program will use the default ones.
height: 10
width: 10
cell_size: 20

# This text will show under the maze. Can be blank.
credits: "@daily_maze"

# Twitter API tokens
twitter:
  api_key: "YOUR API KEY"
  api_key_secret: "YOUR API KEY SECRET"
  access_token: "YOUR ACCESS TOKEN"
  access_token_secret: "YOUR ACCESS TOKEN SECRET"

# Messages to write on Twitter posts. Every post will contain the generic text and the specific text of the current day
messages:
  morning:
    generic_text: "Good morning, humans!"
    monday: "But... it's monday :("
    tuesday: "Take a cup of coffee!"
    wednesday: ""
    thursday: ""
    friday: "Finally it's friday!"
    saturday: "Time to rest!"
    sunday: ""
  evening:
    generic_text: "Good evening, humans!"
    monday: "The worst day is over! :D"
    tuesday: ""
    wednesday: ""
    thursday: ""
    friday: "Good weekend!"
    saturday: ""
    sunday: "Oh no! Tomorrow... :_("